permalink: /:year/:month/:day/:title.html

# 当修改文件时重新生成站点
auto: true
# markdown: rdiscount
markdown: kramdown
pygments: true
paginate: 12

production_url: http://yansong.me
excerpt_separator: ""

author:
    name : yss
    email : yss.nelson@gmail.com
    github : https://github.com/yss
    weibo: http://weibo.com/yssnelson
    company: http://www.meituan.com

domain: yansong.me
